- name: Download Docker installer
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker
    mode: 0555

- name: Install Docker
  shell: /tmp/get-docker creates=/usr/bin/docker

- name: Make sure Docker is running
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes